---
title: "`r params$targetGen`"
output: 
    rmarkdown::pdf_document:
      latex_engine: pdflatex
      dev: png
geometry: "left=1cm, right=1cm, top=0cm, bottom=0cm"
params:
  targetGen: "Ceratium"
  begin: 1995
  end: 2020
  gridX: 15000
  gridY: 15000
---

```{r setup, include=FALSE, warning=FALSE}
rm(list = ls())

# Set options of chunks and figures
knitr::opts_chunk$set(fig.pos = 'H')

# Require packages
require(tidyverse)
require(rworldxtra)

# Load functions from R script
source("../scripts/WP4_phy_functions_needed.R")

# Load phy data set from working directory
load(file.path("../data/raw_data/phy_gen.Rdata"))

```

```{r doCalculations, message=FALSE, warning=FALSE, include=FALSE}
# Create zeroes:
phy_c_g <- completeZeros_gen(phy_gen, params$targetGen, params$begin:params$end) 

# This df contains duplicates from different datasets that have the same location and time, which seems unlikely
dup_zero_g <- phy_c_g %>% 
  arrange(genus, date, xUTM, yUTM, occurs, season) %>%
  select(-abbr) %>%
  duplicated %>% which
# Create the df with duplicates
dbs_zero_g <- phy_c_g %>% 
  arrange(genus, date, xUTM, yUTM, occurs, season) %>%
  ungroup() %>%
  slice(sort(c(dup_zero_g, dup_zero_g-1))) 

# Write this out in a csv. To check for later purposes.
#path_dup = "p:/emodnet_biology/dataproducts/phytoplankton/obisdata/duplicates/"

#if(length(dbs_zero_g$occurs) > 0){
#    
#    write.csv(dbs_zero_g, 
#              paste0(path_dup, 
#                     "Dupl_", 
#                     params$targetGen, " ", 
#                     params$begin, "-", params$end, ".csv"), 
#              row.names = FALSE)
#  }   

# Here we remove the duplicates that have the same location and time in different datasets 
phy_c_g <- phy_c_g %>%
  distinct(genus, date, xUTM, yUTM, date_year, season, occurs, .keep_all = TRUE)

# #############################################################################
# Include the gridnr in the dataframe
# #############################################################################
grconv <- co2gr(phy_c_g$xUTM, phy_c_g$yUTM, params$gridX, params$gridY)  
phy_c_g$gridnr <- grconv$gridnr
phy_c_g$middleXgrid <- grconv$middleXgrid
phy_c_g$middleYgrid <- grconv$middleYgrid
  
# Create a csv file for Leuven to interpolate
#path_out = "p:/emodnet_biology/dataproducts/phytoplankton/obisdata/csv-files/"
#write.csv(phy_c_g, paste0(path_out, params$targetGen, "-", params$begin, "-", params$end, ".csv"), row.names = FALSE)

# Determine height for first plot
height_plot1 <- (2+0.5*length(unique(phy_c_g$abbr))) # Size of height plot 1

# #############################################################################
# calculate time-series and effort per season
# ############################################################################# 
phy_ts_eff <- time_effort(phy_c_g)

# #############################################################################
# calculate no. of species per event, per grid, effort per gridcell and mean occurrence per grid
# #############################################################################
phy_effort <- effort_function(phy_c_g) 
phy_effort_season <- effort_season(phy_c_g)


```


## Time series of data availability per season including effort

```{r plot1a, echo=FALSE, fig.height = height_plot1, fig.fullwidth = TRUE, warning=FALSE, results='asis', dpi = 184}
# Plot 1a: plot the relative abundance per season / per year for each genera and dataset + EFFORT
plot_ts_eff(phy_ts_eff, params$targetGen, params$begin, params$end)
```


## Average distribution per season

```{r plot1b, echo=FALSE, fig.height = 2, fig.width = 6, warning=FALSE, results='asis', dpi = 184}
# Plot 1b: plot the relative abundance per season 
plot_season_eff(phy_ts_eff, params$targetGen, params$begin, params$end)
```


## Distribution map 2a: presence/absence points with effort (as color) 

```{r plot2a, echo=FALSE, warning = FALSE, fig.width = 6, dpi = 184}
# Plot 2a: the presence/absence map (points on grid raster) including effort
plot_abun_point(df = phy_effort, pres_abse = "pres_abse", Size = "effort", long = "middleXgrid", 
                lat = "middleYgrid", params$targetGen)
```

## Distribution map 2b: presence/absence points with effort (as color) per season

```{r plot2b, echo=FALSE, warning = FALSE, fig.width = 6, fig.height=10, dpi = 184}
# Plot 2b: the presence/absence map (points on grid raster) per season
plot_abun_point_season(df = phy_effort_season, "pres_abse", "effort", "middleXgrid", "middleYgrid", params$targetGen)
```
