---
title: "`r params$targetGen`"
output: 
    rmarkdown::pdf_document:
      latex_engine: pdflatex
geometry: "left=1cm, right=1cm, top=0cm, bottom=0cm"
params:
  targetGen: "Protoperidinium"
  begin: 1995
  end: 2020
  gridX: 35000
  gridY: 35000
  borderx_min: -800000
  borderx_max: 1250000
  bordery_min: 5250000
  bordery_max: 6950000
---

```{r setup, include=FALSE, warning=FALSE}
# Set options of chunks and figures
knitr::opts_chunk$set(fig.pos = 'H')

# Require packages
require(tidyverse)
require(rworldxtra)

dataDir <- "data/derived_data/"
# Load phy data set from working directory
load(file.path(dataDir, "phy_gen.Rdata"))

```

```{r functions needed for analysis, include=FALSE, warning=FALSE}
# Complete zeroes function for genus:
completeZeros_gen <- function(df, gen, year){
  selectedDatasets <- df %>% 
    ungroup() %>%
    dplyr::filter(genus ==  gen) %>%
    distinct(datasetID) %>% unlist() %>% unname()
  df %>%
    dplyr::filter(year %in% year) %>%
    dplyr::filter(datasetID %in% selectedDatasets) %>%
    group_by(datasetID, abbr, year) %>%
    tidyr::complete(nesting(genus),         # these will be completed, with their occurrence
                    nesting(date, xUTM, yUTM, season, eventid),   # Combinations of these parameters are to be found
                    fill = list(occurrence = 0)) %>% 
    ungroup() %>%
    filter(genus == gen) %>%
    ungroup()
}


# Function returns a named list containing the grid numbers corresponding to the 
# coordinates of the input, as well as the parameters of the transformation that 
# will be needed for the back-transformation.
co2gr<-function(lon,lat,fdx,fdy){
  xgrid <- floor(lon/fdx)
  ygrid <- floor(lat/fdy)
  mnx <- min(xgrid)
  mny <- min(ygrid)
  xgrid <- xgrid-mnx+1
  ygrid <- ygrid-mny+1
  xgm <- max(xgrid)
  ygm <- max(ygrid)
  middleXgrid <- (xgrid + mnx - 1)*fdx + (fdx/2)  # Hier bereken ik het middelpunt, deze formule komt uit gr2co (zie hieronder)
  middleYgrid <- (ygrid + mny - 1)*fdy + (fdy/2)
  gridnr <- (ygrid-1)*xgm+xgrid
  return(data.frame(gridnr, middleXgrid, middleYgrid))
}

# Create data for time series plot including effort
time_effort <- function(df) {
  df %>% ungroup() %>%
    group_by(datasetID, abbr, year, season) %>%
    summarize(effort_per_season = n(), positives = sum(occurrence == 1)) %>%
    mutate(rel_abun = positives/effort_per_season) %>% ungroup() %>%
    mutate(season = factor(season, levels = rev(c("autumn", "summer", "spring", "winter")))) 
}


# Create dataset for effort plot
effort_function <- function(df, tax_level){
  df %>% ungroup() %>%
    group_by(gridnr, middleXgrid, middleYgrid) %>%  # alle bewerkingen per grid cell en aphiaID
    summarise(effort = n_distinct(eventid),
              effort_n = n(),
              pres_abse = mean(occurrence)) %>%
    ungroup()
}

effort_season <- function(df){
  df %>% ungroup() %>%
    group_by(gridnr, season, middleXgrid, middleYgrid) %>%  # alle bewerkingen per grid cell en aphiaID
    summarise(effort = n_distinct(eventid),
              effort_n = n(),
              pres_abse = mean(occurrence)) %>%
    ungroup() %>%
    mutate(season = factor(season, levels = rev(c("autumn", "summer", "spring", "winter")))) 
}

```


```{r doCalculations, message=FALSE, warning=FALSE, include=FALSE}
# Create zeroes:
phy_c_g <- completeZeros_gen(phy_gen, params$targetGen, params$begin:params$end) 

# This df contains duplicates from different datasets that have the same location and time, which seems unlikely
dup_zero_g <- phy_c_g %>% 
  arrange(genus, date, xUTM, yUTM, occurrence, season) %>%
  select(-datasetID) %>%
  duplicated %>% which
# Create the df with duplicates
dbs_zero_g <- phy_c_g %>% 
  arrange(genus, date, xUTM, yUTM, occurrence, season) %>%
  ungroup() %>%
  slice(sort(c(dup_zero_g, dup_zero_g-1))) 

# Write this out in a csv. To check for later purposes.
#path_dup = "p:/emodnet_biology/dataproducts/phytoplankton/obisdata/duplicates/"

#if(length(dbs_zero_g$occurs) > 0){
#    
#    write.csv(dbs_zero_g, 
#              paste0(path_dup, 
#                     "Dupl_", 
#                     params$targetGen, " ", 
#                     params$begin, "-", params$end, ".csv"), 
#              row.names = FALSE)
#  }   

# Here we remove the duplicates that have the same location and time in different datasets 
phy_c_g <- phy_c_g %>%
  distinct(genus, date, xUTM, yUTM, year, season, occurrence, .keep_all = TRUE)

# #############################################################################
# Include the gridnr in the dataframe
# #############################################################################
grconv <- co2gr(phy_c_g$xUTM, phy_c_g$yUTM, params$gridX, params$gridY)  
phy_c_g$gridnr <- grconv$gridnr
phy_c_g$middleXgrid <- grconv$middleXgrid
phy_c_g$middleYgrid <- grconv$middleYgrid
  
# Create a csv file for Leuven to interpolate
#path_out = "p:/emodnet_biology/dataproducts/phytoplankton/obisdata/csv-files/"
#write.csv(phy_c_g, paste0(path_out, params$targetGen, "-", params$begin, "-", params$end, ".csv"), row.names = FALSE)

# #############################################################################
# calculate time-series and effort per season
# ############################################################################# 
phy_ts_eff <- time_effort(phy_c_g)

# #############################################################################
# calculate no. of species per event, per grid, effort per gridcell and mean occurrence per grid
# #############################################################################
phy_effort <- effort_function(phy_c_g) 
phy_effort_season <- effort_season(phy_c_g)


```

```{r functions needed for plotting, include=FALSE, warning=FALSE}
# Determine height for first plot
height_plot1 <- (2+0.4*length(unique(phy_ts_eff$datasetID))) # Size of height plot 1

# Create background map from Rworldxtra
data("countriesHigh") 

# Transform the coordinates of the Rworldxtra map to our preferred code (32631)
bgmap <- countriesHigh %>%
  sf::st_as_sf() %>%
  sf::st_transform(32631)

# Plot 1a: plot the occurrence per season / per year for each species including the effort
plot_ts_eff <- function(df, sp_gen, begin, end) {
  ggplot(df, aes(year, season)) +
    geom_point(aes(size = effort_per_season, color = rel_abun)) +
    scale_shape_manual(values = c(21)) +
    scale_size("Effort per season", range = c(0.25,3.5), 
               breaks = c(0,1,10,50,100,500), labels = c(0,1,10,50,100,500), limits = c(0,500)) +
    scale_colour_continuous("Relative abundance", type = "viridis") +
    scale_x_continuous(limits = c(begin, end)) +
    facet_grid(abbr ~ .) +
    theme(strip.text.y = element_text(angle = 0),
          legend.position = "bottom") +
    labs(subtitle = sp_gen, x = "Year", y = "Season")
}


# Plot 1b: plot the occurrence over season for each species including the effort
plot_season_eff <- function(df, sp_gen, begin, end) {
  ggplot(df, aes(season, rel_abun)) +
    geom_boxplot() +
    theme(strip.text.y = element_text(angle = 0),legend.position = "bottom") +
    labs(subtitle = sp_gen, x = "Season", y = "relative abun")
}

# Plot 2c: the presence/absence map (points on grid raster) including effort (as size)
plot_abun_point <- function(df, pres_abse, Size, long, lat, speciesName, borderx_min, borderx_max, bordery_min, bordery_max){
  ggplot(data = df) +
    geom_point(aes_string(x = long, y = lat, colour = pres_abse, size = Size), show.legend = TRUE) +
    scale_colour_continuous("Relative abundance", type = "viridis", limits = c(0,1)) +
    scale_size_continuous("Events/grid", range = c(0.25, 3.5),
                          breaks = c(1,10,50,100,500,1000,1500), labels = c(1,10,50,100,500,1000,1500), limits = c(1,1500)) +
    guides(size = guide_legend(order = 1)) +
    #guides(colour = guide_legend(override.aes = list(breaks = c(0.0,0.25,0.5,0.75,1.0)))) +
    labs(title = speciesName, x = "Longitude", y = "Latitude") + 
    geom_sf(data = bgmap, fill = "darkgrey")  +
    theme(panel.background = element_rect(fill = "lightgrey"),
          panel.grid = element_line(color = "black"),
          legend.position = "bottom") +
    coord_sf(xlim = c(borderx_min, borderx_max), ylim = c(bordery_min, bordery_max)) 
}

# Plot 2d: the presence/absence map (points on grid raster) including effort (as size)
plot_abun_point_season <- function(df, pres_abse, Size, long, lat, speciesName, borderx_min, borderx_max, bordery_min, bordery_max){
  ggplot(data = df) +
    geom_point(aes_string(x = long, y = lat, colour = pres_abse, size = Size), show.legend = TRUE) +
    scale_colour_continuous("Relative abundance", type = "viridis", limits = c(0,1)) +
    scale_size_continuous("Events/grid", range = c(0.25, 3.5),
                          breaks = c(1,10,50,100,500,1000), labels = c(1,10,50,100,500,1000), limits = c(1,1000)) +
    labs(title = speciesName, x = "Longitude", y = "Latitude") + 
    facet_wrap(~season, nrow = 2) +
    geom_sf(data = bgmap, fill = "darkgrey")  +
    theme(panel.background = element_rect(fill = "lightgrey"),
          panel.grid = element_line(color = "black", size = 0.1),
          legend.position = "bottom") +
    coord_sf(xlim = c(borderx_min, borderx_max), ylim = c(bordery_min, bordery_max))
}

```

## Time series of data availability per season including effort

```{r plot1a, echo=FALSE, fig.height = height_plot1, fig.fullwidth = TRUE, warning=FALSE, results='asis', dpi = 184}
# Plot 1a: plot the relative abundance per season / per year for each genera and dataset + EFFORT
plot_ts_eff(phy_ts_eff, params$targetGen, params$begin, params$end)
```


## Average distribution per season

```{r plot1b, echo=FALSE, fig.height = 2, fig.width = 6, warning=FALSE, results='asis', dpi = 184}
# Plot 1b: plot the relative abundance per season 
plot_season_eff(phy_ts_eff, params$targetGen, params$begin, params$end)
```


## Distribution map 2a: presence/absence points with effort (as color) 

```{r plot2a, echo=FALSE, warning = FALSE, fig.width = 12, dpi = 184}
# Plot 2a: the presence/absence map (points on grid raster) including effort
plot_abun_point(df = phy_effort, pres_abse = "pres_abse", Size = "effort", long = "middleXgrid", 
                lat = "middleYgrid", params$targetGen, 
                params$borderx_min, params$borderx_max, params$bordery_min, params$bordery_max)
```

## Distribution map 2b: presence/absence points with effort (as color) per season

```{r plot2b, echo=FALSE, warning = FALSE, fig.width = 16, dpi = 184}
# Plot 2b: the presence/absence map (points on grid raster) per season
plot_abun_point_season(df = phy_effort_season, "pres_abse", "effort", "middleXgrid", "middleYgrid", params$targetGen, 
                params$borderx_min, params$borderx_max, params$bordery_min, params$bordery_max)
```
